#!/bin/sh
#------------------------------------------------------------------------------
#
# MyRPM - Rpm Utilities
# Copyright (c) Jean-Marie RENOUARD 2014 - LightPath
# Contact : Jean-Marie Renouard <jmrenouard at gmail.com>
#
# This program is open source, licensed under the Artistic Licence v2.0.
#
# Artistic Licence 2.0
# Everyone is permitted to copy and distribute verbatim copies of 
# this license document, but changing it is not allowed.
#
#------------------------------------------------------------------------------

PASSWD_FILE=$HOME/.passwords
LOCAL=${1:-"/var/www/html/repo"}
HOST=jmrenouard.fr
REMOTE=/fastecks.com/repo
USER=$(grep -vE "^\s*#" $PASSWD_FILE|grep "ftpuser"| cut -d= -f2)
PASS=$(grep -vE "^\s*#" $PASSWD_FILE|grep "ftppassword"| cut -d= -f2)

lftp -e "mirror -R $LOCAL $REMOTE;quit" -u $USER,$PASS $HOST
