#!/bin/bash
#------------------------------------------------------------------------------
#
# MyRPM - Rpm Utilities
# Copyright (c) Jean-Marie RENOUARD 2014 - LightPath
# Contact : Jean-Marie Renouard <jmrenouard at gmail.com>
#
# This program is open source, licensed under the Artistic Licence v2.0.
#
# Artistic Licence 2.0
# Everyone is permitted to copy and distribute verbatim copies of 
# this license document, but changing it is not allowed.
#
#------------------------------------------------------------------------------

printUsage() {
	echo "rpmFactory fonctionne avec un fichier de configuration."	
	echo "rpmFactory construit un RPM et compile ce dernier sur un serveur distant"	
	exit 0
}

[ -n "$MYRPM" ] || printUsage


#$MYRPM -N $APPLI -V $VERSION -R $RELEASE -S "$SUMMARY" -D "$DESCRIPTION" -n -d . -r . -x "$EXCLUDE" -C "$CHANGELOG" --requires="$REQUIRES" --pre-script="pre.sh" --post-script="post.sh"
$MYRPM -N $APPLI -V $VERSION -R $RELEASE -S "$SUMMARY" -D "$DESCRIPTION" -n -c -b -d . -r . -x "$EXCLUDE" -C "$CHANGELOG" --requires="$REQUIRES" --pre-script="pre.sh" --post-script="post.sh"
